


import { Product } from '../types';

export const ebooks: Product[] = [
  {
    id: 'e-005',
    name: 'वशीकरण PDF हिंदी e-book',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए। (PDF प्रारूप)',
    mrp: 119,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096760/IMG_20251026_151309_500_rdoeed.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1yuRhw8MTXyGvsGSP1X1AKn6T3Pobjt9j',
    reviewVideoUrl: 'https://res.cloudinary.com/de2eehtiy/video/upload/v1764095597/5_6129929173419956762_1_hd1rpt.mp4',
    isTrending: true
  },
  {
    id: 'e-006',
    name: '80+ मार्केटिंग कोर्स 50+ सॉफ्टवेयर',
    description: 'अपनी जिंदगी बदलने का गोल्डन चांस ना गवाए आज ही pdf बुक सबसे कम कीमत में खरीदें',
    mrp: 199,
    discountPercentage: 55,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764500967/IMG-20251012-WA0001_igbbs1.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/file/d/12STvEwZbHzHe7CqIMHnAasK75FLwcOne/view?usp=drivesdk',
    reviewVideoUrl: ''
  },
  {
    id: 'e-007',
    name: 'Numerology',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए अपना वर्तमान और भविष्य जाने और सही दिशा तय करें',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096760/IMG_20251026_151244_044_hqcutl.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1zUppw5sQ5rnX1-WntXIWts0nqnbpTZI6',
    reviewVideoUrl: ''
  },
  {
    id: 'e-008',
    name: 'vastu shatra PDF कोर्स',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096759/IMG_20251026_151201_802_kje8zs.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1LygtZY16MJEOTy1BR8vp0WKPBXdGSPyk',
    reviewVideoUrl: ''
  },
  {
    id: 'e-009',
    name: 'yog and ayurved pdf e-book',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096760/IMG_20251026_151251_233_nd5llj.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/145k8K3nCTbz87h_uf2PoMt36aViOrbqc',
    reviewVideoUrl: ''
  },
  {
    id: 'e-010',
    name: 'computer fundamentals PDF हिंदी भाषा में फुल गाइड',
    description: 'इस कोर्स में आप कंप्यूटर full बेसिक कोर्स सीखेंगे और कंप्यूटर हार्डवेयर के बारे में जानेंगे',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764500966/IMG-20250708-WA0001_poitfu.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/file/d/12XFAd3jn-YvLmlXEB6IUK8uu-nEs2dMp/view?usp=drivesdk',
    reviewVideoUrl: ''
  },
  {
    id: 'e-011',
    name: 'real estate Full हिंदी e-book',
    description: 'इस कोर्स को पढ़कर आप बेसिक से एडवांस लेवल तक जमीन खरीदना बेचना प्रॉपर्टी खरीदना बेचना सीख पाएंगे',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096764/IMG_20251026_151257_573_xwxlq2.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1uUPj2avVDT0P4pXIwv-0PHrrcoU0Ui4J',
    reviewVideoUrl: ''
  },
  {
    id: 'e-012',
    name: 'तंत्र मंत्र यंत्र संग्रह pdf E-book guide',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096761/IMG_20251026_151353_124_z88tzx.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1OJ307ZVPoyjG-LJkLyySssbWwVXSvFLN',
    reviewVideoUrl: ''
  },
  {
    id: 'e-013',
    name: 'english speaking full गाइड हिंदी में',
    description: 'इस कोर्स को पढ़कर आप बेसिक से एडवांस लेवल इंग्लिश बोलना सीख जाएंगे',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096763/IMG_20251026_151502_157_uo9tra.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1q61eivPUko7dnPXnqGjMuxEN0WsY6ru0',
    reviewVideoUrl: ''
  },
  {
    id: 'e-014',
    name: 'reels bundle pdf e-book हिन्दी में',
    description: 'इस कोर्स को पढ़कर आप ऑनलाइन पैसे कमाना सीख जाएंगे',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096761/IMG_20251026_151429_038_dibqgb.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/file/d/15rVSMs9lRLoSurI0ZgznYdBP_0zzgKKE/view?usp=drivesdk',
    reviewVideoUrl: ''
  },
  {
    id: 'e-015',
    name: 'specal वशीकरण PDF हिंदी भाषा में',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096760/IMG_20251026_151324_124_gjoov8.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1yuRhw8MTXyGvsGSP1X1AKn6T3Pobjt9j',
    reviewVideoUrl: ''
  },
  {
    id: 'e-016',
    name: 'astrology full PDF कोर्स',
    description: 'सभी समस्याओं का समाधान एवम उपाय एक ही बुक में पाए अपने जीवन के वर्तमान भविष्य के बारे में जाने',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096761/IMG_20251026_151303_245_ne5tqb.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1zUppw5sQ5rnX1-WntXIWts0nqnbpTZI6',
    reviewVideoUrl: ''
  },
  {
    id: 'e-017',
    name: 'धर्म ज्ञान फुल गाइड',
    description: 'यहां पर आप हिंदू धर्म से संबंधित सभी ज्ञान एक ही जगह पर पाए सबसे कम कीमत में',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096762/IMG_20251026_151347_680_fsfjpl.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1Eu35RhG7ckwtxwscrASPAFctlo-snD27',
    reviewVideoUrl: ''
  },
  {
    id: 'e-018',
    name: 'digital products pdf e-book हिन्दी भाषा में',
    description: 'digital ज्ञान संपूर्ण ज्ञान एक ही जगह पर पाए',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096763/IMG_20251026_151451_507_uaie8f.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/file/d/15rVSMs9lRLoSurI0ZgznYdBP_0zzgKKE/view?usp=drivesdk',
    reviewVideoUrl: ''
  },
  {
    id: 'e-019',
    name: 'kids work sheet 500+',
    description: 'बच्चों का दिमाग तेज करने के लिए ड्राइंग महत्वपूर्ण है इसे जरूर use करना चाहिए',
    mrp: 29,
    discountPercentage: 20,
    colors: [],
    imageUrl1: 'https://res.cloudinary.com/de2eehtiy/image/upload/v1764096763/IMG_20251026_151443_141_w0egnl.jpg',
    imageUrl2: '',
    category: 'Tantra Mantra Yantra E-book',
    productType: 'DIGITAL',
    googleDriveLink: 'https://drive.google.com/drive/folders/1YUo4bICDzgIdWDaut980HKSI8q4XFrAo',
    reviewVideoUrl: ''
  }
];